# Generated by Django 5.2.3 on 2025-06-28 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="client_number",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type_id",
            field=models.SmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="mail",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cliente_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
