# Generated by Django 5.2.3 on 2025-07-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_mesero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="phone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
