services:
  web:
    build: .
    container_name: order_system
    volumes:
      - .:/app:cached
    ports:
      - "8000:8000"
    environment:
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
