# Generated by Django 5.2.3 on 2025-07-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_rename_movimientoinsumo_actualizacioninventario"),
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Insumos",
            new_name="Insumo",
        ),
    ]
