# Generated by Django 5.2.3 on 2025-07-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0004_alter_insumo_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="DetalleVenta",
        ),
        migrations.DeleteModel(
            name="Venta",
        ),
    ]
