# Generated by Django 5.2.3 on 2025-07-16 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0005_remove_venta_producto_remove_venta_usuario_and_more"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actualizacioninventario",
            name="venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos",
                to="ventas.venta",
            ),
        ),
    ]
